<?php 


// $str = str_pad(1234, 3, '0', STR_PAD_LEFT);
// echo decrypt('eyJpdiI6InhlNmZGdGErMDNOcm9TdHl1OHR6VGc9PSIsInZhbHVlIjoib1hYSUZKdURKYUxQV0ZLbFdDTzBFdEEyclZHaWk3aHRMNndBTlBqcVUxZz0iLCJtYWMiOiI3NjdlZTczZWZhYTIyOTM3YTkwYjMwZGY5ZWNhN2IxNGU5MmJiZDZhZDhkNmNhZDA2OTI4ODdlN2U3NmMzY2VkIn0=');